### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by zeinalii** [data301-2020-winter1/course-project-solo_303#1]
## High priority (must-fix)          
- [x] Make sure to add the figures (referencing with numbers) in your report file.     
- [x] Please add some introductory information about your data and the questions that you want to ask. You have suddenly jumped into the project.   Make it as if you are telling a story. Explain the importance of those questions and why exactly you chose those visualization methods.     
- [x] add references to your report. Also, whenever you cite a reference,   make sure to mention it in your report text.          

## Medium Priority (should-fix)    

 - [x] You did a really good job analyzing the data but your report is not well-written.  You need to first explain the data (and its features/attributes), then explain your questions, and finally explain your analysis method.

 - [x] When you explain the data, make sure to explain each feature (columns) of the data.

 - [x] The box plot on line 172 does not quite answer your question. Generally, box plots are used for something completely different, not calculating the average age.

 - [x] "What are the 5 most popular Classifications?" You need to explain what is your definition of popularity. What do the numbers show in that graph? 

- [x] What do the colors represent in the last graph?

- [x] Add a conclusion at the end of your analysis and explain whether your analysis answered your questions or not. And add some suggestions for future works.

**Comment by catsforjodi** [comment]
@zeinalii Thanks for the feedback! 
You mentioned my analysis was not story like or narrative at all. If I structure the file into the following sections/headlines (with thorough explanation within each), would that be better?:

1. Information About the Data
2. Research Questions
3. Analysis
4. Conclusion

Also, Should I label which diagrams are Task 4 (EDA) and Task 5 (Research)? I feel like it seems to mixed up right now.

**Comment by zeinalii** [comment]
yes. it doesn't have to be too much text. Just give it a little bit of
structure.
